SELECT TOP (1000) [BookID]
      ,[ISBNID]
      ,[Name]
      ,[Description]
      ,[Publish_Date]
      ,[Genre]
      ,[Age_restriction]
      ,[Category]
      ,[ColorTag]
  FROM [libraryDBS].[dbo].[Book]
